name: Build, Test And Push Docker

on:
  push:
    tags:
      - "*.*.*"
env:
  DOCKER_IMAGE_NAME: ipmdecisions/userprovisionservice
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      # - name: Clean with dotnet
      #   run: dotnet clean H2020.IPMDecisions.UPR.API
      # - name: Test with dotnet
      #   run: dotnet test H2020.IPMDecisions.UPR.Tests --filter Category!=Docker
      - name: Build image with latest
        run: docker build . -f "./Docker/Dockerfile" -t "${{ env.DOCKER_IMAGE_NAME }}:latest" --build-arg BUILDER_VERSION=latest --build-arg RELEASE_DATE=${{ steps.current-time.outputs.time }}
      - name: Build image with tag ${{ steps.vars.outputs.tag }}
        run: docker build . -f "./Docker/Dockerfile" -t "${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.tag }}" --build-arg BUILDER_VERSION=${{ steps.vars.outputs.tag }} --build-arg RELEASE_DATE=${{ steps.current-time.outputs.time }}
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Push to docker hub tag ${{ steps.vars.outputs.tag }}
        uses: actions-hub/docker@master
        with:
          args: push ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
